- name: Copy files from host
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '/home/ms/web_notes_mysql/Dockerfile', dest: '/home/ec2-user/Dockerfile' }
    - { src: '/home/ms/web_notes_mysql/requirements.txt', dest: '/home/ec2-user/requirements.txt' }
    - { src: '/home/ms/web_notes_mysql/notes_mysql.py', dest: '/home/ec2-user/notes_mysql.py' }
